[package]
name = "depends-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
ctrlc = "3.5.0"
log = "0.4.28"
scopeguard="1.2.0"
thiserror = "2.0.16"

[dev-dependencies]
env_logger = "0.11.8"
